# Generated by Django 5.1 on 2024-09-05 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('email', models.EmailField(db_index=True, max_length=70, unique=True)),
                ('telephone', models.CharField(db_index=True, max_length=15)),
                ('photo', models.ImageField(upload_to='media/')),
                ('statut', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=30)),
                ('auteur', models.CharField(max_length=30)),
                ('nbr_en_stock', models.IntegerField()),
                ('description', models.TextField(max_length=500)),
                ('isbn', models.CharField(db_index=True, max_length=13, unique=True)),
                ('photo', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_retour', models.DateField()),
                ('date_emprunt', models.DateField(auto_now_add=True)),
                ('statut_emprunt', models.CharField(max_length=20)),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livre.beneficiaire')),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livre.livre')),
            ],
        ),
        migrations.CreateModel(
            name='Bibliothecaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('email', models.EmailField(db_index=True, max_length=70, unique=True)),
                ('telephone', models.CharField(db_index=True, max_length=15)),
                ('photo', models.ImageField(upload_to='media/')),
                ('livres', models.ManyToManyField(blank=True, related_name='gerer', to='livre.livre')),
            ],
        ),
    ]
