# Generated by Django 5.1 on 2024-09-07 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livre', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprunt',
            name='beneficiaire',
        ),
        migrations.RemoveField(
            model_name='emprunt',
            name='livre',
        ),
        migrations.AlterField(
            model_name='bibliothecaire',
            name='email',
            field=models.EmailField(db_index=True, max_length=70),
        ),
        migrations.CreateModel(
            name='Emprunter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('email', models.EmailField(db_index=True, max_length=70)),
                ('telephone', models.CharField(db_index=True, max_length=15)),
                ('photo', models.ImageField(upload_to='media/')),
                ('date_retour', models.DateField()),
                ('date_emprunt', models.DateField()),
                ('statut_emprunt', models.CharField(max_length=20)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livre.livre')),
            ],
        ),
        migrations.DeleteModel(
            name='Beneficiaire',
        ),
        migrations.DeleteModel(
            name='Emprunt',
        ),
    ]
