# Generated by Django 5.1 on 2024-09-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livre', '0002_remove_emprunt_beneficiaire_remove_emprunt_livre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunter',
            name='statut_emprunt',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('retournee', 'Retournée'), ('en_retard', 'En retard')], default='en_cours', max_length=20),
        ),
    ]
