# Generated by Django 5.1 on 2024-09-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livre', '0003_alter_emprunter_statut_emprunt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunter',
            name='statut_emprunt',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('retournee', 'Retourné'), ('en_retard', 'En retard')], default='en_cours', max_length=20),
        ),
    ]
