# Generated by Django 5.1 on 2024-09-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livre', '0004_alter_emprunter_statut_emprunt'),
    ]

    operations = [
        migrations.CreateModel(
            name='authUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('mot_de_passe', models.CharField(max_length=30)),
            ],
        ),
    ]
